### ISSUE TITLE
run-sql doesn't work anymore

### ISSUE THREAD

**Issue by Biktop** [TopCS/grunt-pg-utils#7]
I tried using run-sql task and now it doesn't work. Problem is related to 'String' library. The library (in this commit https://github.com/jprichardson/string.js/commit/b17972070bbc3b6ec50c20e2222b6b0f51620cc0) was broken compatibility and now function *S.template* replaces keys that do not exist with empty string.
Meanwhile run-sql depends on *template* function that returns keys without changing.

**Comment by claudyus** [comment]
Can you provide a PR or a patch?

**Comment by Biktop** [comment]
I tried master version and now I see that commit (https://github.com/TopCS/grunt-pg-utils/commit/869b763c862570463e4c5cf996b59869ea9b80ab) fixed the issue. It would be great if the latest version was tagged for npm usage.

**Comment by claudyus** [comment]
I just release the 0.1.4 tagged version. Have fun!
